[project]
name = "exchange-rates"
version = "0.1.0"
description = "Exchange rates for some currencies"
authors = ["Sergey Mikhno <sergey.mikhno@galenica.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
dash = "2.14.2.*"
jupyterlab = "4.0.9.*"
dash-html-components = "2.0.0.*"
aiohttp = "3.9.1.*"
pandas = "2.1.3.*"
pip = "23.3.1.*"
matplotlib = "3.8.2.*"
plotly = "5.18.0.*"
pyinstaller = "6.2.0.*"


[pypi-dependencies]
html-table-parser-python3 = "~=0.3.1"
